# Autogenerated wrapper script for flux_core_jll for powerpc64le-linux-gnu
export flux, libflux_core

using libsodium_jll
using ZeroMQ_jll
using czmq_jll
using Jansson_jll
using Libuuid_jll
using Lz4_jll
using Hwloc_jll
using SQLite_jll
using Lua_jll
JLLWrappers.@generate_wrapper_header("flux_core")
JLLWrappers.@declare_executable_product(flux)
JLLWrappers.@declare_library_product(libflux_core, "libflux-core.so.2")
function __init__()
    JLLWrappers.@generate_init_header(libsodium_jll, ZeroMQ_jll, czmq_jll, Jansson_jll, Libuuid_jll, Lz4_jll, Hwloc_jll, SQLite_jll, Lua_jll)
    JLLWrappers.@init_executable_product(
        flux,
        "bin/flux",
    )

    JLLWrappers.@init_library_product(
        libflux_core,
        "lib/libflux-core.so",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@generate_init_footer()
end  # __init__()
